### ISSUE TITLE
Optional is not quite the same as `| undefined`

### ISSUE THREAD

**Issue by iansan5653** [David-Else/modern-typescript-with-examples-cheat-sheet#1]
Just wanted to mention something I've run into a couple times that you might want to note: the optional modified (`?`) is not exactly the same as adding `| undefined` to the type of the member or parameter. `| undefined` will require the parameter to be explicitly passed as `undefined`, while `?` allows leaving it out entirely:

```ts
function exampleA(x: number | undefined): void { x; }

function exampleB(x?: number): void { x; }

exampleA(); // errors
exampleB(); // ok
exampleA(undefined); // ok
exampleB(undefined); // ok
```

**Comment by David-Else** [comment]
Cheers! I made an update, what do you think?

Optional parameter `?` automatically adds `| undefined`

```ts
type User = {
  firstName: string;
  lastName?: string; // same as `string | undefined`
};
```

In JavaScript, every function parameter is optional, when left off their value is `undefined`. We can get this functionality in TypeScript by adding a `?` to the end of parameters we want to be optional. This is different from adding `| undefined` which requires the parameter to be explicitly passed as `undefined`

```ts
function fn1(x: number | undefined): void {
  x;
}

function fn2(x?: number): void {
  x;
}

fn1(); // Error
fn2(); // OK
fn1(undefined); // OK
fn2(undefined); // OK
```

**Comment by iansan5653** [comment]
Looks good!

**Comment by David-Else** [comment]
Cool. I will close the issue, thanks again for your feedback.

I just added a ton more examples and did a lot of re-writing, so even more feedback is welcome!
